AWSTemplateFormatVersion: "2010-09-09"
Description: "SwiftLine Lex V2 Bot Definition via CloudFormation"

Parameters:
  BotName:
    Type: String
  LexRoleArn:
    Type: String
  LambdaFulfillmentArn:
    Type: String
  BotAliasName:
    Type: String
  AssessmentTag:
    Type: String
  ProjectTag:
    Type: String
  CreatedByTag:
    Type: String
  LexLogGroupArn:
    Type: String

Resources:
  # 1. THE BOT
  LexBot:
    Type: "AWS::Lex::Bot"
    Properties:
      Name: !Ref BotName
      RoleArn: !Ref LexRoleArn
      DataPrivacy:
        ChildDirected: false
      IdleSessionTTLInSeconds: 300
      BotTags:
        - Key: Assessment
          Value: !Ref AssessmentTag
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Created_by
          Value: !Ref CreatedByTag
      BotLocales:
        - LocaleId: "en_US"
          NluConfidenceThreshold: 0.40
          Intents:
            - Name: "WelcomeIntent"
              SampleUtterances:
                - Utterance: "Hi"
                - Utterance: "Hello"
                - Utterance: "Main Menu"
              FulfillmentCodeHook:
                Enabled: true 
            - Name: "GetOrderStatus"
              SampleUtterances:
                - Utterance: "What is the status of my order {TrackingID}"
                - Utterance: "Track my order with ID {TrackingID}"
                - Utterance: "Where is my package"
                - Utterance: "Track order"
                - Utterance: "I want to track my order"
              FulfillmentCodeHook:
                Enabled: true
              Slots:
                - Name: "TrackingID"
                  SlotTypeName: "AMAZON.AlphaNumeric"
                  ValueElicitationSetting:
                    SlotConstraint: "Required"
                    PromptSpecification:
                      MaxRetries: 2
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Please provide your tracking ID (e.g., SWL-2024-AIR-001234)."
              SlotPriorities:
                - Priority: 1
                  SlotName: "TrackingID"
            - Name: "EndConversationIntent"
              SampleUtterances:
                - Utterance: "No"
                - Utterance: "No thanks"
                - Utterance: "I am done"
                - Utterance: "Bye"
              FulfillmentCodeHook:
                Enabled: true
            - Name: "FallbackIntent"
              ParentIntentSignature: "AMAZON.FallbackIntent"

  # 2. THE VERSION 
  BotVersion:
    Type: "AWS::Lex::BotVersion"
    Properties:
      BotId: !Ref LexBot
      BotVersionLocaleSpecification:
        - LocaleId: "en_US"
          BotVersionLocaleDetails:
            SourceBotVersion: "DRAFT"
    Metadata:
      Comment: "Version 1 with Logging Enabled"

  # 3. THE ALIAS
  BotAlias:
    Type: "AWS::Lex::BotAlias"
    Properties:
      BotAliasName: !Ref BotAliasName
      BotId: !Ref LexBot
      BotVersion: !GetAtt BotVersion.BotVersion 
      
      # === NEW: CONVERSATION LOGGING ===
      ConversationLogSettings:
        TextLogSettings:
          - Enabled: true
            Destination:
              CloudWatch:
                CloudWatchLogGroupArn: !Ref LexLogGroupArn
                LogPrefix: "ConversationLogs"
      
      BotAliasLocaleSettings:
        - LocaleId: "en_US"
          BotAliasLocaleSetting:
            Enabled: true
            CodeHookSpecification:
              LambdaCodeHook:
                CodeHookInterfaceVersion: "1.0"
                LambdaArn: !Ref LambdaFulfillmentArn

Outputs:
  BotId:
    Value: !Ref LexBot
  BotAliasId:
    Value: !Ref BotAlias
  BotAliasArn:
    Value: !Sub "arn:aws:lex:${AWS::Region}:${AWS::AccountId}:bot-alias/${LexBot}/${BotAlias}"